### ISSUE TITLE
Assign Project Tasks and Responsibilities

### ISSUE THREAD

**Issue by SD-github21** [TyeStanley/GroupProject3#2]
## **Assign Project Tasks and Responsibilities Class Meeting updated 8/18/22**

**CLIENT SIDE:**
* Tye: App.js,  Footer components
* McKinley: Login, Sign Up, Profile/Dashboard components, Nav Bar
* Scott: Restaurant, Home components
* Sapana: Auth.js, mutations + queries (client side)

**SERVER SIDE:**
* Chase: TypeDefs, Resolvers (mutations + queries server side), server.js
* Sapana: server.js, Auth middleware  (server side), config, Models
 
**COMPLETE PRESENTATION POWERPOINT -- IN CLASS ON MONDAY 8/22**

**Comment by Azariill** [comment]
Assignments have been fullfilled.
