### ISSUE TITLE
Setup Images

### ISSUE THREAD

**Issue by Azariill** [TyeStanley/GroupProject3#5]
# We need to implement the ability to load images.  Things to look into 

# Research these
- Multer for graphql/apollo
- File uploads via https://www.apollographql.com/docs/apollo-server/data/file-uploads/

### What we need to accomplish is that the file is uploaded into the public/ folder and the file name is saved into the restaurant in the database.

**Comment by SD-github21** [comment]
I researched into some sites and came up with these sites that looked promising regarding how they discuss this issue:

https://www.apollographql.com/docs/apollo-server/data/file-uploads/
https://github.com/graphql/express-graphql/issues/9
https://www.positronx.io/react-file-upload-tutorial-with-node-express-and-multer/
https://stackoverflow.com/questions/42058634/upload-image-to-graphql-server
https://docs.amplify.aws/guides/api-graphql/image-and-file-uploads/q/platform/js/#creating-the-services

**Comment by Azariill** [comment]
Images have been implemented
