### ISSUE TITLE
Add comments

### ISSUE THREAD

**Issue by Azariill** [TyeStanley/GroupProject3#6]
### Currently UserReview is commented out in the restaurant card because the comment mapping has to be adjusted to fit the new query

**Comment by SD-github21** [comment]
I was able to get most of this code completed. However, comments needs to be mapped within the Restaurant Card component. I was thinking that you might want to have a separate add comments component. The actual mutation of adding a comment works, but there is some challenge with returning it back with the restaurants query. Anywho, I at least got us moving forward on it...hopefully this is helpful!

**Comment by Azariill** [comment]
fixed bugs and finished feature
